sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pJQy4dPhrq5eAo8K580WBIA8gTFqftG1RxdKETVhLQTw/mSKYorRL5UiKrI2OIIW/Uilju6Nz2midorU0dbZGzS+K8gPNVwvNoKqMtKIlpP8BF1sNvl4IRvt9wVRz7IChlDGCcdVXLUqisgyzE09n45SLe8aOG21vDW9cz+l0A9eoC8u0VWGoE1onnqNoNcfiNsYXxTrel0smFNHjJC7lqWGNS0UTPGHFmEjS/M1XT1X8wpSdz8qbevBs3TNbM5Qu3lOZj2WtbmnXg9jR35Nf2IBwpEIh+PavzUUXOx9S7bZtojV17er3gF6PnXrFld4SoL6Qia+RdgqCVhD6mIu1hXkkauuYbz/UvW/EUIVYdMi0frGcMNI+5NbKYzTENwtOz1WSTKdT99z2cw7g+I4eh+oP3N0yh8MA5UH9/v6Lk+tWNmQzlHs6UxUP0JVnbYeBoNJNoYbRC9bJ2biLpt6awnJg1FdF0IA1NdCZycrREDsxPZswMzA+7wnitKtkNt79wrwUAFAHF7KpXarFz5tx3nu49b6dVFDvUgucNWZ01TNLFU1sEQMQ2Z6hljhyCCtWC2xI60f4+9deUlLcAa5VWIop+u2uq7HS4izy77u8OC8gWK8lN9NPL2e8MJfYMIMkCC7IyhAAznYh3UwQqPF4IsljjOxRjL6YfExkDq387w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Mr-Bonaparte-of-Corsica_3236
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy